### ISSUE TITLE
[Question] Spacemouse not detected in the Teleoperation and Imitation Learning demo 

### ISSUE THREAD

**Issue by TTimelord** [isaac-sim/IsaacLab#1009]
Hi! I'm playing with the[ Teleoperation and Imitation Learning demo ](https://isaac-sim.github.io/IsaacLab/source/overview/teleop_imitation.html#teleoperation-and-imitation-learning). I run `./isaaclab.sh -p source/standalone/environments/teleoperation/teleop_se3_agent.py --task Isaac-Lift-Cube-Franka-IK-Rel-v0 --num_envs 1 --teleop_device spacemouse` with a spacemouse connected and get
```
Traceback (most recent call last):
  File "/home/lma326/IsaacLab/source/standalone/environments/teleoperation/teleop_se3_agent.py", line 128, in <module>
    main()
  File "/home/lma326/IsaacLab/source/standalone/environments/teleoperation/teleop_se3_agent.py", line 90, in main
    teleop_interface = Se3SpaceMouse(
  File "/home/lma326/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/devices/spacemouse/se3_spacemouse.py", line 53, in __init__
    self._find_device()
  File "/home/lma326/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/devices/spacemouse/se3_spacemouse.py", line 136, in _find_device
    raise OSError("No device found by SpaceMouse. Is the device connected?")
OSError: No device found by SpaceMouse. Is the device connected?
```
The output of `lsusb`:
```
Bus 001 Device 004: ID 256f:c62e 3Dconnexion SpaceMouse Wireless
```

I installed hidapi with `sudo apt install libhidapi-dev`.

Is there other libraries I'm missing?

**Comment by fliptrail** [comment]
@TTimelord did you find a fix for this? Still happening for me.

**Comment by TTimelord** [comment]
I found that this is not caused by IssacLab. It's due to an incomplete installation of Spacemouse. If I remember correctly, following [this document](https://zhuyifengzju.github.io/deoxys_docs/html/tutorials/using_teleoperation_devices.html#installation) solved the problem
