### ISSUE TITLE
Issue with Streamsdk

### ISSUE THREAD

**Issue by Roythescientist** [isaac-sim/IsaacLab#1060]
Hello, I recently installed Isaac Sim and after successfully installing it and also downloading the datasets I tried teleoperating one of the robots given in the examples using this command:
python -m omnigibson.examples.robots.robot_control_example 
And I got  a module error that omni.usd is not found. Attached is the photo of the error I am getting.

Here is my log:
```
Choose a robot (enter a number from 1 to 11): 10
[INFO] [omnigibson.simulator] ----- Starting OmniGibson. This will take 10-30 seconds... -----
Starting kit application with the following args:  ['/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/apps/omnigibson.kit', '--/app/tokens/exe-path=/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/kit', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True', '--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=False', '--/app/fastShutdown=True', '--ext-folder', '/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts', '--ext-folder', '/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/apps', '--/physics/cudaDevice=0', '--portable']
Passing the following args to the base kit application:  []
[Info] [carb] Logging to file: /home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/kit/logs/Kit/Isaac-Sim/2023.1/kit_20240927_180926.log
2024-09-27 22:09:26 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
[0.027s] Failed to solve some dependencies locally, syncing with extension registry...
[0.028s] [ext: omni.kit.async_engine-0.0.0] startup
[DEBUG] [asyncio] Using selector: EpollSelector
[0.029s] [ext: omni.assets.plugins-0.0.0] startup
[0.030s] [ext: omni.client-1.0.1] startup
[0.034s] [ext: omni.kit.registry.nucleus-0.0.0] startup
2024-09-27 22:09:58 [32,085ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
	[omnigibson-2023.1.1] dependency: (name: 'omni.kit.streamsdk.plugins', tag: '', version: '2.5.2', exact: 1, optional: 0) can't be satisfied. Available versions:
	 - [omni.kit.streamsdk.plugins-2.6.2+105.1.lx64.r] (registry)
	 - [omni.kit.streamsdk.plugins-2.5.1+105.1.lx64.r] (registry)
	 - [omni.kit.streamsdk.plugins-2.5.0+105.1.lx64.r] (registry)
	 - [omni.kit.streamsdk.plugins-2.3.7+105.1.lx64.r] (/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/extscache/omni.kit.streamsdk.plugins-2.3.7+105.1.lx64.r)
	 - [omni.kit.streamsdk.plugins-2.1.3+105.1.lx64.r] (/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/extscache/omni.kit.streamsdk.plugins-2.1.3+105.1.lx64.r)
	 - [omni.kit.streamsdk.plugins-2.0.3+105.0.lx64.r] (registry)

2024-09-27 22:09:58 [32,086ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
[32.093s] Simulation App Starting
Traceback (most recent call last):
  File "/home/Austine/anaconda3/envs/omnigibson/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/Austine/anaconda3/envs/omnigibson/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/Austine/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 154, in <module>
    main()
  File "/home/Austine/OmniGibson/omnigibson/examples/robots/robot_control_example.py", line 93, in main
    env = og.Environment(configs=cfg)
  File "/home/Austine/OmniGibson/omnigibson/utils/python_utils.py", line 90, in wrapper
    func(*values.args, **values.kwargs)
  File "/home/Austine/OmniGibson/omnigibson/envs/env_base.py", line 41, in __init__
    launch_simulator()
  File "/home/Austine/OmniGibson/omnigibson/simulator.py", line 173, in launch_simulator
    og.app = _launch_app()
  File "/home/Austine/OmniGibson/omnigibson/simulator.py", line 90, in _launch_app
    app = lazy.omni.isaac.kit.SimulationApp(config_kwargs, experience=str(kit_file_target.resolve(strict=True)))
  File "/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py", line 214, in __init__
    create_new_stage()
  File "/home/Austine/.local/share/ov/pkg/isaac-sim-2023.1.0-hotfix.1/exts/omni.isaac.kit/omni/isaac/kit/utils.py", line 65, in create_new_stage
    import omni.usd
ModuleNotFoundError: No module named 'omni.usd'
2024-09-27 22:09:58 [32,087ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
```

**Comment by Toni-SM** [comment]
Hi @Roythescientist 

This is a non-Isaac Lab related issue that you need to discuss with the developers of the OmniGibson project on its repository: https://github.com/StanfordVL/OmniGibson.

Just a quick note, latest Isaac Sim version is 4.2.0 and you are using `omnigibson-2023.1.1` which may not be compatible. In any case, ask OmniGibson developers.
