### ISSUE TITLE
/omni.kit.pip_archive/pip_prebundle ruin my pip directory

### ISSUE THREAD

**Issue by robotNo201** [isaac-sim/IsaacLab#1067]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

/omni.kit.pip_archive/pip_prebundle ruin my pip directory, the wrapper override all my conda environment

### Steps to reproduce

Just install omniverse and your virtual environment will be down. 

```
(amass_venv) C:\Users\hankc\code\amass_master\amass>python -m pip --version
Traceback (most recent call last):
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\__main__.py", line 29, in <module>
    from pip._internal.cli.main import main as _main
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_internal\utils\logging.py", line 13, in <module>
    from pip._vendor.rich.console import (
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_vendor\rich\console.py", line 58, in <module>
    from .pretty import Pretty, is_expandable
  File "C:\Users\hankc\anaconda3\envs\amass_venv\lib\site-packages\pip\_vendor\rich\pretty.py", line 31, in <module>
    import attr as _attr_module
  File "C:\Users\hankc\code\Isaaclab\IsaacLab\_isaac_sim/kit/exts/omni.kit.pip_archive/pip_prebundle\attr\__init__.py", line 10, in <module>
    from . import converters, exceptions, filters, setters, validators
  File "C:\Users\hankc\code\Isaaclab\IsaacLab\_isaac_sim/kit/exts/omni.kit.pip_archive/pip_prebundle\attr\converters.py", line 10, in <module>
    from ._compat import _AnnotationExtractor
  File "C:\Users\hankc\code\Isaaclab\IsaacLab\_isaac_sim/kit/exts/omni.kit.pip_archive/pip_prebundle\attr\_compat.py", line 21, in <module>
    from typing_extensions import Protocol
  File "C:\Users\hankc\code\Isaaclab\IsaacLab\_isaac_sim/kit/exts/omni.kit.pip_archive/pip_prebundle\typing_extensions.py", line 995
    def TypedDict(typename, fields=_marker, /, *, total=True, closed=False, **kwargs):
```
### System Info

Describe the characteristic of your environment:

- Commit: [e.g. 8f3b9ca]
- Isaac Sim Version: newest
- OS: win11
- GPU: rtx4090
- CUDA: 12.6
- GPU Driver: 530

### Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by Toni-SM** [comment]
Hi @robotNo201 

> Just install omniverse and your virtual environment will be down.

Could you please provide more detailed/reproductible steps? 
What link(s) you followed to install Isaac Sim and Isaac Lab, as weel to setup the conda env?
