### ISSUE TITLE
[Bug Report] Unexpected simulator shutdown

### ISSUE THREAD

**Issue by RiccardoZuppetti** [isaac-sim/IsaacLab#1185]
### Describe the bug

After following the guide for installing IsaacLab (all steps succeeded without any error), checking that the installation was successful and referring to that section in the guide (https://isaac-sim.github.io/IsaacLab/source/setup/installation/binaries_installation.html#verifying-the-isaac-lab-installation), immediately after starting up the simulator closes almost immediately, reporting the error below.

### Steps to reproduce

I've given the following command in order to verify the installation
```
cd IsaacLab
./isaaclab.sh -p source/standalone/tutorials/00_sim/create_empty.py
```

and this is what is shown by the terminal:

```
[10.709s] app ready
[12.508s] Simulation App Startup Complete
[12.886s] [ext: omni.physx.fabric-106.0.16] startup
Traceback (most recent call last):
  File "/home/ubuntu/IsaacLab/source/standalone/tutorials/00_sim/create_empty.py", line 59, in <module>
    main()
  File "/home/ubuntu/IsaacLab/source/standalone/tutorials/00_sim/create_empty.py", line 47, in main
    sim.reset()
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/simulation_context.py", line 404, in reset
    self.render()
  File "/home/ubuntu/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/simulation_context.py", line 467, in render
    self.physics_sim_view.update_articulations_kinematic()
AttributeError: 'SimulationView' object has no attribute 'update_articulations_kinematic'
2024-10-08 10:29:09 [13,762ms] [Warning] [carb] [Plugin: omni.sensors.tiled.plugin] Module /home/ubuntu/.local/share/ov/pkg/isaac-sim-4.0.0/extscache/omni.sensors.tiled-0.0.3+106.0.0.lx64.r/bin/libomni.sensors.tiled.plugin.so remained loaded after unload request
2024-10-08 10:29:09 [13,770ms] [Warning] [carb] [Plugin: omni.spectree.delegate.plugin] Module /home/ubuntu/.local/share/ov/pkg/isaac-sim-4.0.0/kit/exts/omni.usd_resolver/bin/libomni.spectree.delegate.plugin.so remained loaded after unload request
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-08 10:29:09 [13,773ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-10-08 10:29:10 [14,258ms] [Warning] [carb] Recursive unloadAllPlugins() detected!

```

### System Info

Describe the characteristic of your environment:

- Commit: [d18f0c266be39998630aea0efc3853725b056715]
- Isaac Sim Version: [4.0.0]
- OS: [Ubuntu 22.04]
- GPU: [A10G]
- CUDA: [12.6]
- GPU Driver: [560.35.03 ]

### Additional context

This problem is encountered if I try to run other demo or environment.

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] Criteria 1
- [ ] Criteria 2

**Comment by Toni-SM** [comment]
Hi @RiccardoZuppetti 

Please, note that you are using [unsupported Isaac Sim version 4.0.0](https://isaac-sim.github.io/IsaacLab/source/setup/installation/index.html). Update your Isaac Sim to the lates 4.2.0 version
