### ISSUE TITLE
[Bug Report] cant import usd file in version 1.2

### ISSUE THREAD

**Issue by amatsukaze233** [isaac-sim/IsaacLab#1286]
### Describe the bug

occur when open a new file 

### Steps to reproduce
![QQ图片20241022172701](https://github.com/user-attachments/assets/ab3d6728-9e6b-430a-84ac-faa6d67da53e)

```




2024-10-22 09:46:58 [210,024ms] [Warning] [pxr.Semantics] pxr.Semantics is deprecated - please use Semantics instead
[211.420s] [ext: omni.physx.fabric-106.1.9] startup
[INFO]: Setup complete...
[281.884s] Simulation is stopped. The app will keep running with physics disabled. Press Ctrl+C or close the window to exit the app.
2024-10-22 09:48:14 [285,880ms] [Warning] [omni.usd] Unexpected reference count of 2 for UsdStage 'anon:0000017559DED370:World0.usd' while being closed in UsdContext (this may indicate it is still resident in memory).
2024-10-22 09:48:14 [286,374ms] [Warning] [omni.isaac.core.simulation_context.simulation_context] A new stage was opened, World or Simulation Object are invalidated and you would need to initialize them again before using them.
Traceback (most recent call last):
  File "C:\Users\Administrator\IsaacLab2\source\extensions\omni.isaac.lab\omni\isaac\lab\sim\simulation_context.py", line 221, in <lambda>
    lambda *args, obj=weakref.proxy(self): obj._app_control_on_stop_callback(*args),
  File "C:\Users\Administrator\IsaacLab2\source\extensions\omni.isaac.lab\omni\isaac\lab\sim\simulation_context.py", line 622, in _app_control_on_stop_callback
    self.render()
  File "C:\Users\Administrator\IsaacLab2\source\extensions\omni.isaac.lab\omni\isaac\lab\sim\simulation_context.py", line 465, in render
    if self.physics_sim_view is not None and self.is_playing():
  File "f:/anaconda3/envs/isaaclab2/lib/site-packages/isaacsim/exts/omni.isaac.core/omni/isaac/core/simulation_context/simulation_context.py", line 369, in physics_sim_view
    return self._physics_sim_view
AttributeError: 'SimulationContext' object has no attribute '_physics_sim_view'. Did you mean: 'physics_sim_view'?
Traceback (most recent call last):
  File "C:\Users\Administrator\IsaacLab2\source\standalone\tutorials\00_sim\create_empty.py", line 59, in <module>
    main()
  File "C:\Users\Administrator\IsaacLab2\source\standalone\tutorials\00_sim\create_empty.py", line 54, in main
    sim.step()
  File "C:\Users\Administrator\IsaacLab2\source\extensions\omni.isaac.lab\omni\isaac\lab\sim\simulation_context.py", line 420, in step
    self.render()
  File "C:\Users\Administrator\IsaacLab2\source\extensions\omni.isaac.lab\omni\isaac\lab\sim\simulation_context.py", line 465, in render
    if self.physics_sim_view is not None and self.is_playing():
  File "f:/anaconda3/envs/isaaclab2/lib/site-packages/isaacsim/exts/omni.isaac.core/omni/isaac/core/simulation_context/simulation_context.py", line 369, in physics_sim_view
    return self._physics_sim_view
AttributeError: 'SimulationContext' object has no attribute '_physics_sim_view'. Did you mean: 'physics_sim_view'?
2024-10-22 09:48:15 [286,750ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,751ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,753ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,754ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,754ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,755ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,756ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,756ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,757ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,758ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,758ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,759ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-22 09:48:15 [286,759ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-10-22 09:48:15 [286,901ms] [Warning] [carb] Recursive unloadAllPlugins() detected!






```

### System Info

- Commit: [e.g. 8f3b9ca]
- Isaac Sim Version: 4.2  by pip install isaacsim-rl isaacsim-replicator isaacsim-extscache-physics isaacsim-extscache-kit-sdk isaacsim-extscache-kit isaacsim-app --extra-index-url https://pypi.nvidia.com
- OS: windows10
- GPU:2080ti
- CUDA: 12.7
- GPU Driver: 565.90

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Does your asset file already have a physics scene in it? If yes, you should remove it.
