### ISSUE TITLE
Issue on page /source/setup/installation/pip_installation.html

### ISSUE THREAD

**Issue by 181404010226** [isaac-sim/IsaacLab#1472]
I used the following command to install and encountered omni.kit.usd missing error
```
conda create -n isaaclab python=3.10 -y
conda activate isaaclab

pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cu121

pip install --upgrade pip
pip install isaacsim==4.2.0.2 --extra-index-url https://pypi.nvidia.com

sudo apt-get update
sudo apt install cmake build-essential -y

git clone https://github.com/isaac-sim/IsaacLab.git
cd IsaacLab
./isaaclab.sh --install 
```

```
(isaaclab) root@autodl-container-1cf345b42f-02a6504f:~/IsaacLab# python source/standalone/tutorials/00_sim/spawn_prims.py 
[WARN][AppLauncher]: There are no arguments attached to the ArgumentParser object. If you have your own arguments, please load your own arguments before calling the `AppLauncher.add_app_launcher_args` method. This allows the method to check the validity of the arguments and perform checks for argument names.
[INFO][AppLauncher]: Loading experience file: /root/IsaacLab/source/apps/isaaclab.python.kit
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Loading user config located at: '/root/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/data/Kit/Isaac-Sim/4.2/user.config.json'
[Info] [carb] Logging to file: /root/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/logs/Kit/Isaac-Sim/4.2/kit_20241128_152829.log
2024-11-28 07:28:29 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
2024-11-28 07:28:37 [7,823ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
    [isaaclab.python-1.3.0] dependency: 'omni.physx.bundle' = { version='^' } can't be satisfied. Available versions:
     (none found)
 Synced registries:
     - kit/default         : found 388 packages 
     - kit/sdk             : found 317 packages 
     - kit/community       : found 384 packages 

2024-11-28 07:28:37 [7,823ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
```

**Comment by Toni-SM** [comment]
Hi @181404010226 

You also need to install the Isaac Sim - Python packages cached extension dependencies as mentioned in point 3 in https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html#installation-using-pip

**Comment by 181404010226** [comment]
@Toni-SM I used the following command to completely reinstall it, but it didn't seem to work and the error content didn't change. In addition, the gymnasium has a version error, but this error can be ignored when my previous issue was answered

```
conda create -n isaaclab python=3.10 -y
conda activate isaaclab

pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cu121

pip install --upgrade pip
pip install isaacsim==4.2.0.2 --extra-index-url https://pypi.nvidia.com

pip install isaacsim-extscache-physics==4.2.0.2 isaacsim-extscache-kit==4.2.0.2 isaacsim-extscache-kit-sdk==4.2.0.2 --extra-index-url https://pypi.nvidia.com

sudo apt-get update
sudo apt install cmake build-essential -y

git clone https://github.com/isaac-sim/IsaacLab.git
cd IsaacLab
./isaaclab.sh --install rl_games

export OMNI_KIT_ACCEPT_EULA=YES

isaacsim
```
```

Successfully built omni-isaac-lab_tasks rl-games gym robomimic rsl-rl egl_probe promise pathtools
Installing collected packages: pytz, pathtools, gym_notices, egl_probe, tzdata, termcolor, smmap, shortuuid, setproctitle, sentry-sdk, pygame, psutil, protobuf, promise, gymnasium, gym, docker-pycreds, Click, tensorboardX, pandas, gitdb, skrl, GitPython, wandb, stable-baselines3, rsl-rl, robomimic, rl-games, omni-isaac-lab_tasks
  Attempting uninstall: psutil
    Found existing installation: psutil 6.1.0
    Uninstalling psutil-6.1.0:
      Successfully uninstalled psutil-6.1.0
  Attempting uninstall: protobuf
    Found existing installation: protobuf 4.25.5
    Uninstalling protobuf-4.25.5:
      Successfully uninstalled protobuf-4.25.5
  Attempting uninstall: gymnasium
    Found existing installation: gymnasium 0.29.0
    Uninstalling gymnasium-0.29.0:
      Successfully uninstalled gymnasium-0.29.0
  Attempting uninstall: omni-isaac-lab_tasks
    Found existing installation: omni-isaac-lab_tasks 0.10.13
    Uninstalling omni-isaac-lab_tasks-0.10.13:
      Successfully uninstalled omni-isaac-lab_tasks-0.10.13
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
omni-isaac-lab 0.27.15 requires gymnasium==0.29.0, but you have gymnasium 1.0.0 which is incompatible.
Successfully installed Click-8.1.7 GitPython-3.1.43 docker-pycreds-0.4.0 egl_probe-1.0.2 gitdb-4.0.11 gym-0.23.1 gym_notices-0.0.8 gymnasium-1.0.0 omni-isaac-lab_tasks-0.10.13 pandas-2.2.3 pathtools-0.1.2 promise-2.3 protobuf-3.20.3 psutil-5.9.8 pygame-2.1.0 pytz-2024.2 rl-games-1.6.1 robomimic-0.3.0 rsl-rl-2.0.2 sentry-sdk-2.19.0 setproctitle-1.3.4 shortuuid-1.0.13 skrl-1.3.0 smmap-5.0.1 stable-baselines3-2.4.0 tensorboardX-2.6.2.2 termcolor-2.5.0 tzdata-2024.2 wandb-0.12.21
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
[INFO] Running inside a docker container. Skipping VSCode settings setup.
[INFO] To setup VSCode settings, run 'isaaclab -v'.
(isaaclab) root@autodl-container-2ce641b020-fa7ed2dd:~/IsaacLab# python source/standalone/tutorials/00_sim/create_empty.py

By installing or using Omniverse Kit, I agree to the terms of NVIDIA OMNIVERSE LICENSE AGREEMENT (EULA)
in https://docs.omniverse.nvidia.com/platform/latest/common/NVIDIA_Omniverse_License_Agreement.html

Do you accept the EULA? (Yes/No): yes
The EULA was accepted.

[WARN][AppLauncher]: There are no arguments attached to the ArgumentParser object. If you have your own arguments, please load your own arguments before calling the `AppLauncher.add_app_launcher_args` method. This allows the method to check the validity of the arguments and perform checks for argument names.
[INFO][AppLauncher]: Loading experience file: /root/IsaacLab/source/apps/isaaclab.python.kit
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
[Info] [carb] Logging to file: /root/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/logs/Kit/Isaac-Sim/4.2/kit_20241129_091842.log
2024-11-29 01:18:42 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
2024-11-29 01:18:55 [13,497ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
    [isaaclab.python-1.3.0] dependency: 'semantics.schema.property' = { version='^' } can't be satisfied. Available versions:
     (none found)
 Synced registries:
     - kit/default         : found 388 packages 
     - kit/sdk             : found 317 packages 
     - kit/community       : found 384 packages 

2024-11-29 01:18:55 [13,497ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
Traceback (most recent call last):
  File "/root/IsaacLab/source/standalone/tutorials/00_sim/create_empty.py", line 29, in <module>
    app_launcher = AppLauncher(args_cli)
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 113, in __init__
    self._create_app()
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 607, in _create_app
    self._app = SimulationApp(self._sim_app_config, experience=self._sim_experience_file)
  File "/root/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py", line 214, in __init__
    from .utils import create_new_stage, open_stage, set_livesync_stage
  File "/root/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.kit/omni/isaac/kit/utils.py", line 17, in <module>
    from omni.kit.usd import layers
ModuleNotFoundError: No module named 'omni.kit.usd'
2024-11-29 01:18:55 [13,502ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
(isaaclab) root@autodl-container-2ce641b020-fa7ed2dd:~/IsaacLab# 
```

**Comment by Toni-SM** [comment]
Hi @181404010226 

What is the `pip list` output?

**Comment by 181404010226** [comment]
@Toni-SM 
```

(base) root@autodl-container-7e674e82f3-fa3bab60:~# conda activate isaaclab
(isaaclab) root@autodl-container-7e674e82f3-fa3bab60:~# pip list
Package                    Version        Editable project location
-------------------------- -------------- ------------------------------------------------------
absl-py                    2.1.0
antlr4-python3-runtime     4.9.3
boto3                      1.35.71
botocore                   1.35.71
certifi                    2024.8.30
charset-normalizer         3.4.0
click                      8.1.7
cloudpickle                3.1.0
contourpy                  1.3.1
cycler                     0.12.1
decorator                  5.1.1
docker-pycreds             0.4.0
egl_probe                  1.0.2
einops                     0.8.0
Farama-Notifications       0.0.4
filelock                   3.13.1
fonttools                  4.55.0
fsspec                     2024.2.0
gitdb                      4.0.11
GitPython                  3.1.43
grpcio                     1.68.0
gym                        0.23.1
gym-notices                0.0.8
gymnasium                  1.0.0
h5py                       3.12.1
hidapi                     0.14.0.post4
huggingface-hub            0.26.3
hydra-core                 1.3.2
idna                       3.10
imageio                    2.36.1
imageio-ffmpeg             0.5.1
isaacsim                   4.2.0.2
isaacsim-app               4.2.0.2
isaacsim-asset             4.2.0.2
isaacsim-benchmark         4.2.0.2
isaacsim-code-editor       4.2.0.2
isaacsim-core              4.2.0.2
isaacsim-cortex            4.2.0.2
isaacsim-example           4.2.0.2
isaacsim-extscache-kit-sdk 4.2.0.2
isaacsim-extscache-physics 4.2.0.2
isaacsim-gui               4.2.0.2
isaacsim-kernel            4.2.0.2
isaacsim-replicator        4.2.0.2
isaacsim-rl                4.2.0.2
isaacsim-robot             4.2.0.2
isaacsim-robot-motion      4.2.0.2
isaacsim-robot-setup       4.2.0.2
isaacsim-ros1              4.2.0.2
isaacsim-ros2              4.2.0.2
isaacsim-sensor            4.2.0.2
isaacsim-storage           4.2.0.2
isaacsim-template          4.2.0.2
isaacsim-test              4.2.0.2
isaacsim-utils             4.2.0.2
Jinja2                     3.1.3
jmespath                   1.0.1
kiwisolver                 1.4.7
Markdown                   3.7
MarkupSafe                 2.1.5
matplotlib                 3.9.2
moviepy                    2.1.1
mpmath                     1.3.0
networkx                   3.2.1
numpy                      1.26.4
nvidia-cublas-cu12         12.1.3.1
nvidia-cuda-cupti-cu12     12.1.105
nvidia-cuda-nvrtc-cu12     12.1.105
nvidia-cuda-runtime-cu12   12.1.105
nvidia-cudnn-cu12          9.1.0.70
nvidia-cufft-cu12          11.0.2.54
nvidia-curand-cu12         10.3.2.106
nvidia-cusolver-cu12       11.4.5.107
nvidia-cusparse-cu12       12.1.0.106
nvidia-nccl-cu12           2.20.5
nvidia-nvjitlink-cu12      12.1.105
nvidia-nvtx-cu12           12.1.105
omegaconf                  2.3.0
omni-isaac-lab             0.27.15        /root/IsaacLab/source/extensions/omni.isaac.lab
omni-isaac-lab_assets      0.1.4          /root/IsaacLab/source/extensions/omni.isaac.lab_assets
omni-isaac-lab_tasks       0.10.13        /root/IsaacLab/source/extensions/omni.isaac.lab_tasks
omniverse-kit              106.1.0.140981
onnx                       1.16.1
opencv-python              4.10.0.84
orjson                     3.10.12
osqp                       0.6.7.post3
packaging                  24.2
pandas                     2.2.3
pathtools                  0.1.2
pillow                     10.4.0
pip                        24.3.1
prettytable                3.3.0
proglog                    0.1.10
promise                    2.3
protobuf                   3.20.3
psutil                     5.9.8
pygame                     2.1.0
pyglet                     1.5.29
pyparsing                  3.2.0
pyperclip                  1.9.0
python-dateutil            2.9.0.post0
python-dotenv              1.0.1
pytz                       2024.2
PyYAML                     6.0.2
qdldl                      0.1.7.post4
regex                      2024.11.6
requests                   2.32.3
rl_games                   1.6.1
robomimic                  0.3.0
rsl_rl                     2.0.2
s3transfer                 0.10.4
safetensors                0.4.5
scipy                      1.14.1
sentry-sdk                 2.19.0
setproctitle               1.3.4
setuptools                 75.1.0
shortuuid                  1.0.13
six                        1.16.0
skrl                       1.3.0
smmap                      5.0.1
stable_baselines3          2.4.0
sympy                      1.13.1
tensorboard                2.18.0
tensorboard-data-server    0.7.2
tensorboardX               2.6.2.2
tensordict                 0.5.0
termcolor                  2.5.0
tokenizers                 0.20.3
toml                       0.10.2
torch                      2.4.0+cu121
torchvision                0.19.0
tqdm                       4.67.1
transformers               4.46.3
trimesh                    4.5.3
triton                     3.0.0
typing_extensions          4.9.0
tzdata                     2024.2
urllib3                    2.2.3
wandb                      0.12.21
wcwidth                    0.2.13
Werkzeug                   3.1.3
wheel                      0.44.0
(isaaclab) root@autodl-container-7e674e82f3-fa3bab60:~# 
```

**Comment by Toni-SM** [comment]
Hi @181404010226 

From your pip list output, the `isaacsim-extscache-kit` is missing.
Please, make sure that all the Isaac Sim - Python packages cached extension dependencies (as mentioned in point 3 in https://docs.omniverse.nvidia.com/isaacsim/latest/installation/install_python.html#installation-using-pip) are installed
