### ISSUE TITLE
Running ```add_cubes.py```, isaac_sim stuck. And  running ./isaaclab.sh --install, an error message "No such file or directory" appears.

### ISSUE THREAD

**Issue by ecstayalive** [isaac-sim/IsaacLab#1490]
I followed the [tutorial](https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/binaries_installation.html#verifying-the-isaac-sim-installation) to install isaac_sim with isaac_lab, i successfully installed isaac_sim 4.2 and was able to add simple items to isaac_sim.

### Describe the bug
I met two problems:
Firstly, when I run the following command to check whether python is working properly, Isaac_sim freeze. Here is the command  ```${ISAACSIM_PYTHON_EXE} ${ISAACSIM_PATH}/standalone_examples/api/omni.isaac.core/add_cubes.py```. After a certain period of time, isaac_sim will exit automatically, and the terminal will report the following errors:
```
2024-12-02 11:54:18 [560,920ms] [Warning] [omni.usd] Warning: in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </World/defaultGroundPlane>: Could not open asset @http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2/Isaac/Environments/Grid/default_environment.usd@ for reference introduced by @anon:0x3f2a85a0:World0.usd@</World/defaultGroundPlane>. (recomposing stage on stage @anon:0x3f2a85a0:World0.usd@ <0x3c850dd0>)
Traceback (most recent call last):
  File "/home/ecstayalive/.local/share/ov/pkg/isaac-sim-4.2.0/standalone_examples/api/omni.isaac.core/add_cubes.py", line 53, in <module>
    my_world.scene.add_default_ground_plane()
  File "/home/ecstayalive/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.core/omni/isaac/core/scenes/scene.py", line 279, in add_default_ground_plane
    plane = GroundPlane(prim_path=prim_path, name=name, z_position=z_position, physics_material=physics_material)
  File "/home/ecstayalive/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.core/omni/isaac/core/objects/ground_plane.py", line 111, in __init__
    collision_prim_path = get_prim_path(
  File "/home/ecstayalive/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.core/omni/isaac/core/utils/prims.py", line 612, in get_prim_path
    return prim.GetPath()
AttributeError: 'NoneType' object has no attribute 'GetPath'
2024-12-02 11:54:18 [560,939ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-02 11:54:18 [560,940ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-12-02 11:54:18 [561,006ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
```

The second problem I encountered was when I followed the tutorial in the IsaacLab directory to run the ```./isaaclab.sh --install```, The following error occurs:

```find: ‘/home/ecstayalive/Libraries/Nvidia/IsaacLab/_isaac_sim/source/extensions’: No such file or directory```

### Steps to reproduce
I followed the [official tutorial](https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/binaries_installation.html#verifying-the-isaac-sim-installation) and these two problems reproduces every time in my computer.

### System Info
Describe the characteristic of your environment:

- Commit: [4d9914702d84577b59dc468485c6e31f61dcbfde]
- Isaac Sim Version: [4.2.0-rc.17+release.15988.c99988b1.gl]
- OS: [e.g. Ubuntu 20.04]
- GPU: [e.g. RTX 3090]
- CUDA: [e.g. 12.4]
- GPU Driver: [535.183.01]

**Comment by ecstayalive** [comment]
I solve the problem by runing I```sudo ./isaaclab.sh --install```

**Comment by RandomOakForest** [comment]
Good to hear that worked. Thanks for trying this.

**Comment by LittlePotatoChip** [comment]
> I solve the problem by runing `sudo ./isaaclab.sh --install`

I tried this but:

`(isaaclab) potato@potato-MS-7E13:~/workplace/IsaacLab$ sudo ./isaaclab.sh --install
[INFO] Installing extensions inside the Isaac Lab repository...                
./isaaclab.sh: 行 67: python: 未找到命令
[ERROR] Unable to find any Python executable at path: ''
	This could be due to the following reasons:
	1. Conda environment is not activated.
	2. Isaac Sim pip package 'isaacsim-rl' is not installed.
	3. Python executable is not available at the default path: /home/potato/workplace/IsaacLab/_isaac_sim/python.sh
`

**Comment by ecstayalive** [comment]
> isaacsim
First check that you have run the previous installation steps correctly. If the installation procedure is performed correctly, this command will still not install correctly. The bellow is another installation way:
Firstly, modify the setup_python_env.sh file in isaac_sim4.2(you can  find the solution in [issue#516](https://github.com/isaac-sim/IsaacLab/issues/516)):
```diff
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+if [ -n "$ZSH_VERSION" ]; then
+    SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
+else
+    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+fi
```
Then, modify isaaclab.sh file in IsaacLab:
```diff
-export ISAACLAB_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+export ISAACLAB_PATH="$( cd "$( dirname "$0" )" &> /dev/null && pwd )"
```
Then just follow the official installation setps

**Comment by ecstayalive** [comment]
> > I solve the problem by runing `sudo ./isaaclab.sh --install`
> 
> I tried this but:
> 
> `(isaaclab) potato@potato-MS-7E13:~/workplace/IsaacLab$ sudo ./isaaclab.sh --install [INFO] Installing extensions inside the Isaac Lab repository... ./isaaclab.sh: 行 67: python: 未找到命令 [ERROR] Unable to find any Python executable at path: '' This could be due to the following reasons: 1. Conda environment is not activated. 2. Isaac Sim pip package 'isaacsim-rl' is not installed. 3. Python executable is not available at the default path: /home/potato/workplace/IsaacLab/_isaac_sim/python.sh `

First check that you have run the previous installation steps correctly. If the installation procedure is performed correctly, this command will still not install correctly. The bellow is another installation way:
Firstly, modify the setup_python_env.sh file in isaac_sim4.2(you can  find the solution in [issue#516](https://github.com/isaac-sim/IsaacLab/issues/516)):
```diff
-SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+if [ -n "$ZSH_VERSION" ]; then
+    SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
+else
+    SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+fi
```
Then, modify isaaclab.sh file in IsaacLab:
```diff
-export ISAACLAB_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
+export ISAACLAB_PATH="$( cd "$( dirname "$0" )" &> /dev/null && pwd )"
```
Then just follow the official installation setps
