### ISSUE TITLE
[Bug Report] Unable to render 

### ISSUE THREAD

**Issue by Huisouan** [isaac-sim/IsaacLab#1527]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug
![截图 2024-12-12 14-21-43](https://github.com/user-attachments/assets/6e6e9d95-4405-4a21-bf10-4bfeae77c561)
Unable to render the scene with the command 
./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py --task Isaac-Reach-Franka-v0

### System Info

Describe the characteristic of your environment:

- Commit: [e.g. [762f4e3]]
- Isaac Sim Version: [4.2.0.2]
- OS: [Ubuntu 22.04]
- GPU: [e.g. RTX 4090
- CUDA: [e.g. 12.4]
- GPU Driver: [e.g. 550.120]

**Comment by Mayankm96** [comment]
You need to also pass the command `--enable_cameras`.

**Comment by Huisouan** [comment]
tried，still the same problem。

**Comment by Huisouan** [comment]
ps :I was able to train with --headless mode.

**Comment by RandomOakForest** [comment]
Thanks for posting this. Could you please post the full output of the error message you get? It seems the stdout you posted is a partial one. There should be a line with a type of error such as `AssertionError`, etc. for example. Also, if you could try the release [commit for Isaac Lab 1.3](https://github.com/isaac-sim/IsaacLab/releases/tag/v1.3.0) would be appreciated. Thanks!

**Comment by Huisouan** [comment]
it seems like there is also an asset problem.
I uesd another computer,and reporformed this problem
`
(isaaclab) (base) hsh@hsh-MS-7E01:~/Code/IsaacLab$ ./isaaclab.sh -p source/standalone/workflows/rsl_rl/train.py --task Isaac-Reach-Franka-v0
[INFO] Using python from: /home/hsh/miniconda3/envs/isaaclab/bin/python                                                                                          
[INFO][AppLauncher]: Loading experience file: /home/hsh/Code/isaac-rl-lab/source/apps/isaaclab.python.kit
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Loading user config located at: '/home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/data/Kit/Isaac-Sim/4.2/user.config.json'
[Info] [carb] Logging to file: /home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/logs/Kit/Isaac-Sim/4.2/kit_20241214_142554.log
2024-12-14 06:25:54 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
2024-12-14 06:25:54 [4ms] [Warning] [omni.ext.plugin] [ext: unitree_s2r] Extensions config 'extension.toml' doesn't exist '/home/hsh/Code/isaac-rl-lab/source/extensions/unitree_s2r' or '/home/hsh/Code/isaac-rl-lab/source/extensions/unitree_s2r/config'
2024-12-14 06:25:54 [4ms] [Warning] [omni.ext.plugin] [ext: unitree_sdk2_python] Extensions config 'extension.toml' doesn't exist '/home/hsh/Code/isaac-rl-lab/source/extensions/unitree_sdk2_python' or '/home/hsh/Code/isaac-rl-lab/source/extensions/unitree_sdk2_python/config'

|---------------------------------------------------------------------------------------------|
| Driver Version: 550.120       | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA GeForce RTX 4070 Ti SUPER | Yes: 0 |     | 16376   MB | 10de      | 0          |
|     |                                  |        |     |            | 2705      | ec0ca200.. |
|     |                                  |        |     |            | 1         |            |
|=============================================================================================|
| OS: 24.04.1 LTS (Noble Numbat) ubuntu, Version: 24.04.1, Kernel: 6.8.0-50-generic
| XServer Vendor: The X.Org Foundation, XServer Version: 12101011 (1.21.1.11)
| Processor: 13th Gen Intel(R) Core(TM) i7-13700KF | Cores: 16 | Logical: 24
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 64148 | Free Memory: 56052
| Total Page/Swap (MB): 8191 | Free Page/Swap: 8191
|---------------------------------------------------------------------------------------------|
2024-12-14 06:25:58 [3,715ms] [Warning] [omni.replicator.core.scripts.annotators] Annotator PostProcessDispatch is already registered, overwriting annotator template
2024-12-14 06:25:58 [4,012ms] [Warning] [omni.kit.widget.cache_indicator.cache_state_menu] Unable to detect Omniverse Cache Server. File /home/hsh/.nvidia-omniverse/config/omniverse.toml is not found. Consider installing it for better IO performance.
Path http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2 exists and is set as NUCLEUS_ASSET_ROOT_DIR.
[INFO]: Parsing configuration from: <class 'omni.isaac.lab_tasks.manager_based.manipulation.reach.config.franka.joint_pos_env_cfg.FrankaReachEnvCfg'>
[INFO]: Parsing configuration from: omni.isaac.lab_tasks.manager_based.manipulation.reach.config.franka.agents.rsl_rl_ppo_cfg:FrankaReachPPORunnerCfg
[INFO] Logging experiment in directory: /home/hsh/Code/IsaacLab/logs/rsl_rl/franka_reach
Setting seed: 42
[2024-12-14 14:26:03,522][ogn_registration][INFO] - Looking for Python nodes to register in omni.physx.fabric-106.1.9
[2024-12-14 14:26:03,522][ogn_registration][INFO] -  -> Registered nodes from module omni.physxfabric at /home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extsPhysics/omni.physx.fabric
[2024-12-14 14:26:03,522][ogn_registration][INFO] - Registering nodes in /home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extsPhysics/omni.physx.fabric imported as omni.physxfabric with AutoNode config {}
[2024-12-14 14:26:03,522][ogn_registration][INFO] - Registering Python Node Types from omni.physxfabric at /home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extsPhysics/omni.physx.fabric in omni.physx.fabric
[2024-12-14 14:26:03,522][ogn_registration][INFO] - ========================================================================================================================
[2024-12-14 14:26:03,522][ogn_registration][INFO] - No dependency on omni.graph, therefore no nodes to register in omni.physx.fabric
[2024-12-14 14:26:03,522][ogn_registration][INFO] - ...None found, no registration to do
[2024-12-14 14:26:03,522][ogn_registration][INFO] - ...Skipping: No OmniGraph presence in the module omni.physxfabric - No nodes in this module, do not remember it
[2024-12-14 14:26:03,522][ogn_registration][INFO] - Destroying registration record for omni.physx.fabric
[2024-12-14 14:26:03,522][ogn_registration][INFO] - OGN register omni.physx.fabric-106.1.9 took 666109.000000
[INFO]: Base environment:
    Environment device    : cuda:0
    Environment seed      : 42
    Physics step-size     : 0.016666666666666666
    Rendering step-size   : 0.03333333333333333
    Environment step-size : 0.03333333333333333
2024-12-14 06:27:07 [72,958ms] [Warning] [omni.usd] Warning: in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </World/envs/env_0/Robot>: Could not open asset @http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2/Isaac/IsaacLab/Robots/FrankaEmika/panda_instanceable.usd@ for reference introduced by @anon:0x3dbf2af0:World0.usd@</World/envs/env_0/Robot>. (recomposing stage on stage @anon:0x3dbf2af0:World0.usd@ <0x3bf5a930>)

2024-12-14 06:27:07 [73,004ms] [Warning] [omni.isaac.lab.sim.utils] Could not perform 'modify_rigid_body_properties' on any prims under: '/World/envs/env_0/Robot'. This might be because of the following reasons:
    (1) The desired attribute does not exist on any of the prims.
    (2) The desired attribute exists on an instanced prim.
        Discovered list of instanced prim paths: []
2024-12-14 06:27:07 [73,004ms] [Warning] [omni.isaac.lab.sim.utils] Could not perform 'modify_articulation_root_properties' on any prims under: '/World/envs/env_0/Robot'. This might be because of the following reasons:
    (1) The desired attribute does not exist on any of the prims.
    (2) The desired attribute exists on an instanced prim.
        Discovered list of instanced prim paths: []
2024-12-14 06:29:07 [192,376ms] [Warning] [omni.usd] Warning: in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </World/ground>: Could not open asset @http://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.2/Isaac/Environments/Grid/default_environment.usd@ for reference introduced by @anon:0x3dbf2af0:World0.usd@</World/ground>. (recomposing stage on stage @anon:0x3dbf2af0:World0.usd@ <0x3bf5a930>)

[INFO]: Time taken for scene creation : 183.697171 seconds
Error executing job with overrides: []
Traceback (most recent call last):
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/hydra.py", line 91, in hydra_main
    func(env_cfg, agent_cfg, *args, **kwargs)
  File "/home/hsh/Code/IsaacLab/source/standalone/workflows/rsl_rl/train.py", line 101, in main
    env = gym.make(args_cli.task, cfg=env_cfg, render_mode="rgb_array" if args_cli.video else None)
  File "/home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 740, in make
    env = env_creator(**env_spec_kwargs)
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 75, in __init__
    super().__init__(cfg=cfg)
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 116, in __init__
    self.scene = InteractiveScene(self.cfg.scene)
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab/omni/isaac/lab/scene/interactive_scene.py", line 145, in __init__
    self._add_entities_from_cfg()
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab/omni/isaac/lab/scene/interactive_scene.py", line 486, in _add_entities_from_cfg
    asset_cfg.spawn.func(
  File "/home/hsh/Code/isaac-rl-lab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/spawners/from_files/from_files.py", line 145, in spawn_ground_plane
    collision_prim_path = prim_utils.get_prim_path(
  File "/home/hsh/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.core/omni/isaac/core/utils/prims.py", line 612, in get_prim_path
    return prim.GetPath()
AttributeError: 'NoneType' object has no attribute 'GetPath'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-12-14 06:29:07 [192,420ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-12-14 06:29:07 [192,470ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
`

**Comment by RandomOakForest** [comment]
Following up on this, we ran into the holidays and release work, our apologies for the late reply. If this is something you still see in Isaac Sim 4.5 and Isaac Lab 2.0 with the recommended drivers, please let us know and we will investigate. Thank you.

**Comment by RandomOakForest** [comment]
I hope this issue has been resolved with Isaac Sim 4.5 and Isaac Lab 2.0. If this is not the case, please reopen the issue and update your output log. Thanks.
