### ISSUE TITLE
[Bug Report] Failed to solve some dependencies locally, syncing with extension registry...

### ISSUE THREAD

**Issue by GRINGOLOCO7** [isaac-sim/IsaacLab#537]
### Describe the bug
------------------------------------------------------------------------------
I followed the installation for **IsaacLab** using Isaac Sim Binaries ([find it here](https://isaac-sim.github.io/IsaacLab/source/setup/installation/binaries_installation.html)).

Summary of my comands to perform the installation:

```
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1$ ls
apps                   environment.yml     isaac-sim.docker.gui.sh       isaac-sim.headless.websocket.h264.sh  kit                                 PACKAGE-INFO.yaml   setup_python_env.sh
bittle_posvec.npy      extension_examples  isaac-sim.docker.sh           isaac-sim.headless.websocket.sh       launcher.toml                       PACKAGE-LICENSES    standalone_examples
compile_commands.json  exts                isaac-sim.fabric.sh           isaac-sim.selector.sh                 omni.isaac.sim.post.install.log     python.sh           tensorboard
config                 extscache           isaac-sim.gym.sh              isaac-sim.sh                          omni.isaac.sim.post.install.run.sh  requirements.txt    tests
data                   extsPhysics         isaac-sim.headless.native.sh  jupyter_kernel                        omni.isaac.sim.post.install.sh      run_all_tests.sh    tools
docs                   isaacsim            isaac-sim.headless.webrtc.sh  jupyter_notebook.sh                   omni.isaac.sim.warmup.sh            setup_conda_env.sh  VERSION
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1$ git clone https://github.com/isaac-sim/IsaacLab.git
Cloning into 'IsaacLab'...
remote: Enumerating objects: 16102, done.
remote: Counting objects: 100% (1154/1154), done.
remote: Compressing objects: 100% (367/367), done.
remote: Total 16102 (delta 750), reused 1116 (delta 734), pack-reused 14948
Receiving objects: 100% (16102/16102), 24.24 MiB | 6.47 MiB/s, done.
Resolving deltas: 100% (9768/9768), done.
Updating files: 100% (847/847), done.
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1$ cd IsaacLab
(failed reverse-i-search)`ln': ^C -s /home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1 _isaac_sim
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab$ ln -s /home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1 _isaac_sim
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab$ ls
CONTRIBUTING.md  CONTRIBUTORS.md  docker  docs  isaaclab.bat  isaaclab.sh  _isaac_sim  LICENSE  pyproject.toml  README.md  source  tools  VERSION
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab$ sudo apt install cmake build-essential
[sudo] password for gringo: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
build-essential is already the newest version (12.9ubuntu3).
cmake is already the newest version (3.22.1-1ubuntu1.22.04.2).
The following packages were automatically installed and are no longer required:
  libgnome-bg-4-1 libntfs-3g89 libwpe-1.0-1 libwpebackend-fdo-1.0-1 nvidia-firmware-535-535.154.05 tightvncpasswd
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.
gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab$ ./isaaclab.sh -i

```

Then, to check the installation is correct, i am asked to try: .`/isaaclab.sh -p source/standalone/tutorials/00_sim/create_empty.py`
But this comand don't work for me. I get error

```
[0.542s] Failed to solve some dependencies locally, syncing with extension registry...
[0.707s] [ext: omni.kit.async_engine-0.0.0] startup
[0.792s] [ext: omni.assets.plugins-0.0.0] startup
[0.864s] [ext: omni.client-1.0.1] startup
[0.996s] [ext: omni.kit.registry.nucleus-0.0.0] startup
2024-06-18 16:12:26 [4,048ms] [Error] [omni.ext.plugin] Failed to resolve extension dependencies. Failure hints:
	[isaaclab.python-1.0.0] dependency: (name: 'omni.isaac.menu', tag: '', version: '', exact: 0, optional: 0) can't be satisfied. Available versions:
	 (none found)

2024-06-18 16:12:26 [4,048ms] [Error] [omni.kit.app.plugin] Exiting app because of dependency solver failure...
Traceback (most recent call last):
  File "/home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab/source/standalone/tutorials/00_sim/create_empty.py", line 29, in <module>
    app_launcher = AppLauncher(args_cli)
  File "/home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 117, in __init__
    self._create_app()
  File "/home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/app_launcher.py", line 536, in _create_app
    self._app = SimulationApp(self._sim_app_config, experience=self._sim_experience_file)
  File "/home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py", line 195, in __init__
    from .utils import create_new_stage, open_stage, set_livesync_stage
  File "/home/gringo/.local/share/ov/pkg/isaac-sim-2023.1.1/exts/omni.isaac.kit/omni/isaac/kit/utils.py", line 17, in <module>
    from omni.kit.usd import layers
ModuleNotFoundError: No module named 'omni.kit.usd'
2024-06-18 16:12:26 [4,112ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
There was an error running python
```

### System Info
------------------------------------------------------------------------------

- Isaac Sim Version: 2023.1.1-rc.8+2023.1.688.573e0291.tc
- OS: Ubuntu 22.04.4 LTS
- GPU: Geforce RTX ROG STRIX
- NVIDIA-SMI 470.239.06   Driver Version: 470.239.06   CUDA Version: 11.4 

# Notes
---------------------------------------------
Note that my isaac sim installation seams to work just fine. I was able to run existing codes in `standalone_examples `directory such as:
`gringo@kronos:~/.local/share/ov/pkg/isaac-sim-2023.1.1$ ./python.sh standalone_examples/api/omni.isaac.franka/stacking.py
`

**Comment by GRINGOLOCO7** [comment]
Apology, I just founded this issue that has the same problem
https://github.com/isaac-sim/IsaacLab/issues/487
