### ISSUE TITLE
[Bug Report] 'ArticulationData' object has no attribute 'forward_vec_b'

### ISSUE THREAD

**Issue by wty-yy** [isaac-sim/IsaacLab#588]
### Describe the bug

Can't start `Isaac-Ant-v0` and `Isaac-Humanoid-v0` [RL demos](https://isaac-sim.github.io/IsaacLab/source/setup/sample.html#reinforcement-learning) in **IsaacLab**, but [OmniIsaacGymEnvs](https://github.com/isaac-sim/OmniIsaacGymEnvs) is OK.

The error is `AttributeError: 'ArticulationData' object has no attribute 'forward_vec_b'` at "IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/classic/humanoid/mdp/observations.py", line 53.

### Steps to reproduce

Reproduce:
```bash
conda activate isaaclab
./isaaclab.sh -p source/standalone/workflows/rl_games/train.py --task Isaac-Ant-v0 --headless
```

Error messages:
```bash
...
[INFO]: Starting the simulation. This may take a few seconds. Please wait...
[INFO]: Time taken for simulation start : 4.184325 seconds
[INFO] Command Manager:  <CommandManager> contains 1 active terms.
+----------------------------+
|    Active Command Terms    |
+-------+------+-------------+
| Index | Name |     Type    |
+-------+------+-------------+
|   0   | null | NullCommand |
+-------+------+-------------+

[INFO] Action Manager:  <ActionManager> contains 1 active terms.
+----------------------------------+
|  Active Action Terms (shape: 8)  |
+-------+--------------+-----------+
| Index | Name         | Dimension |
+-------+--------------+-----------+
|   0   | joint_effort |         8 |
+-------+--------------+-----------+

Traceback (most recent call last):
  File "/root/IsaacLab/source/standalone/workflows/rl_games/train.py", line 153, in <module>
    main()
  File "/root/IsaacLab/source/standalone/workflows/rl_games/train.py", line 112, in main
    env = gym.make(args_cli.task, cfg=env_cfg, render_mode="rgb_array" if args_cli.video else None)
  File "/root/mambaforge/envs/isaaclab/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 802, in make
    env = env_creator(**env_spec_kwargs)
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 75, in __init__
    super().__init__(cfg=cfg)
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 128, in __init__
    self.load_managers()
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 120, in load_managers
    super().load_managers()
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 216, in load_managers
    self.observation_manager = ObservationManager(self.cfg.observations, self)
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 41, in __init__
    super().__init__(cfg, env)
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/manager_base.py", line 130, in __init__
    self._prepare_terms()
  File "/root/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 254, in _prepare_terms
    obs_dims = tuple(term_cfg.func(self._env, **term_cfg.params).shape[1:])
  File "/root/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/classic/humanoid/mdp/observations.py", line 53, in base_heading_proj
    heading_vec = math_utils.quat_rotate(asset.data.root_quat_w, asset.data.forward_vec_b)
AttributeError: 'ArticulationData' object has no attribute 'forward_vec_b'
```

### System Info

Describe the characteristic of your environment:

- Commit: ffec353e3d9e78a5a53b1d78d52f7e9da0e9cb71
- Isaac Sim Version: 4.0.0-rc.21+4.0.13872.3e3cb0c9.gl#
- OS: ubuntu~20.04.1
- GPU: NVIDIA A800 80GB PCIe
- CUDA: 12.0
- GPU Driver: 525.89.02

### Additional context

Run in `OmniIsaacGymEnvs` is OK:
```bash
cd ~/OmniIsaacGymEnvs/omniisaacgymenvs
python scripts/rlgames_train.py task=Ant headless=True
```

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Dhoeller19** [comment]
Hi @wty-yy,
This problem has been solved recently, please pull latest master.
