### ISSUE TITLE
[Bug Report] "gymnasium.error.Error: Malformed environment ID" But ID is correct

### ISSUE THREAD

**Issue by Aemperior** [isaac-sim/IsaacLab#730]
### Describe the bug

I am trying to run the command
```
./isaaclab.sh -p source/standalone/workflows/rl_games/train.py --task=Isaac-Cartpole-v0 --livestream=2
```
This has worked previously, but now doesn't work anymore.

### Steps to reproduce
* Running the above command on my Ubuntu 20.04 remote workstation in my docker container.

I have successfully followed the [installation guide](https://isaac-sim.github.io/IsaacLab/source/setup/installation/binaries_installation.html), [developers guide](https://isaac-sim.github.io/IsaacLab/source/setup/developer.html), [running existing scripts](https://isaac-sim.github.io/IsaacLab/source/setup/sample.html) guide and everything has worked so far. Suddenly earlier this morning the command I reference above, which has worked previously, no longer works, it gives the error shown below. 

Between the successful execution and now nothing has happened, except from my laptop falling asleep and my ssh-connection subsequently terminating. During my debugging process I have stopped and restarted the docker container. 

```
...
[8.804s] [ext: omni.isaac.utils-1.0.1] startup
[8.821s] [ext: omni.isaac.cloner-0.8.1] startup
[8.832s] [ext: omni.kit.window.stats-0.1.6] startup
[8.848s] [ext: isaaclab.python-1.0.0] startup
[8.860s] Simulation App Starting
[14.319s] app ready
2024-07-25 14:49:26 [14,904ms] [Warning] [omni.kit.imgui_renderer.plugin] _createExtendCursor: No windowing.
2024-07-25 14:49:26 [14,904ms] [Warning] [omni.kit.imgui_renderer.plugin] _createExtendCursor: No windowing.
[16.257s] Simulation App Startup Complete
[16.285s] [ext: omni.services.facilities.base-1.0.4] startup
[16.288s] [ext: omni.services.core-1.9.0] startup
[16.767s] [ext: omni.services.transport.server.base-1.1.1] startup
[16.768s] [ext: omni.kit.streamsdk.plugins-4.4.1] startup
[16.768s] [ext: omni.kit.livestream.core-4.3.5] startup
[16.774s] [ext: omni.services.transport.server.http-1.3.0] startup
[16.793s] [ext: omni.kit.livestream.webrtc-4.1.1] startup

Failed to open [/var/run/utmp]
Active user not found. Using default user [kiosk]Streaming server started.
[16.918s] [ext: omni.services.streaming.manager-0.3.10] startup
[16.925s] [ext: omni.services.streamclient.webrtc-1.3.8] startup
Traceback (most recent call last):
  File "/olympus_ws/git/IsaacLab/source/standalone/workflows/rl_games/train.py", line 57, in <module>
    import omni.isaac.lab_tasks  # noqa: F401
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/__init__.py", line 30, in <module>
    import_packages(__name__, _BLACKLIST_PKGS)
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/importer.py", line 40, in import_packages
    for _ in _walk_packages(package.__path__, package.__name__ + ".", blacklist_pkgs=blacklist_pkgs):
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/importer.py", line 87, in _walk_packages
    yield from _walk_packages(path, info.name + ".", onerror, blacklist_pkgs)
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/importer.py", line 87, in _walk_packages
    yield from _walk_packages(path, info.name + ".", onerror, blacklist_pkgs)
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/importer.py", line 87, in _walk_packages
    yield from _walk_packages(path, info.name + ".", onerror, blacklist_pkgs)
  [Previous line repeated 1 more time]
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/importer.py", line 75, in _walk_packages
    __import__(info.name)
  File "/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/locomotion/velocity/config/anymal_b/__init__.py", line 13, in <module>
    gym.register(
  File "/isaac-sim/kit/python/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 655, in register
    ns, name, version = parse_env_id(id)
  File "/isaac-sim/kit/python/lib/python3.10/site-packages/gymnasium/envs/registration.py", line 276, in parse_env_id
    raise error.Error(
gymnasium.error.Error: Malformed environment ID:     . (Currently all IDs must be of the form [namespace/](env-name)-v(version). (namespace is optional))
...
```

### System Info

Describe the characteristic of your environment:

- Commit: b1be6bb4de595fa9c06d82379b80360befffe360 
- Isaac Sim Version: 4.0.0-rc.21+4.0.13872.3e3cb0c9.glroot
- OS: Remote Ubuntu 20.04 workstation
- GPU: NVIDIA GeForce RTX 3090 
- CUDA: 12.2
- GPU Driver: 535.183.01
- Visualizing using webrtc (livestream=2)
- Using Docker container based on [nvcr.io/nvidia/isaac-sim:4.0.0 image](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/isaac-sim)

### Additional context

I am still able to do `./isaaclab.sh -p source/standalone/demos/quadrupeds.py --livestream=2` without issues. 

I know that "Isaac-Cartpole-v0" is in fact correct, because I copied the below from `.../IsaacLab/docs/source/setup/installation/cloud_installation.rst`:
`./isaaclab.sh -p source/standalone/workflows/rl_games/train.py --task=Isaac-Cartpole-v0`
It is identical to mine except I add the livestream because webrtc. 

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [x] I can run the described command without errors

**Comment by Aemperior** [comment]
Solution was trivial. Some code related to an unrelated extension in `/olympus_ws/git/IsaacLab/source/extensions/omni.isaac.lab_tasks` had been modified and I somehow didn't see this when looking at the git diff. The error message's reference to seemingly unrelated files also threw me off.
