### ISSUE TITLE
[Question] Contact sensor occurs error

### ISSUE THREAD

**Issue by HukoOo** [isaac-sim/IsaacLab#756]
I want to add a contact sensor to the Franka robot's gripper

However, if I add ContactSensorCfg to omni/isaac/lab_tasks/manager_based/manipulation/lift/lift_env_cfg.py as follows,

    @configclass
    class ObjectTableSceneCfg(InteractiveSceneCfg):
        # robots: will be populated by agent env cfg
        robot: ArticulationCfg = MISSING
        # end-effector sensor: will be populated by agent env cfg
        ee_frame: FrameTransformerCfg = MISSING
        # target object: will be populated by agent env cfg
        object: RigidObjectCfg = MISSING

        # Table
        table = AssetBaseCfg(
            prim_path="{ENV_REGEX_NS}/Table",
            init_state=AssetBaseCfg.InitialStateCfg(pos=[0.5, 0, 0], rot=[0.707, 0, 0, 0.707]),
            spawn=UsdFileCfg(usd_path=f"{ISAAC_NUCLEUS_DIR}/Props/Mounts/SeattleLabTable/table_instanceable.usd"),
        )

        # plane
        plane = AssetBaseCfg(
            prim_path="/World/GroundPlane",
            init_state=AssetBaseCfg.InitialStateCfg(pos=[0, 0, -1.05]),
            spawn=GroundPlaneCfg(),
        )

        # lights
        light = AssetBaseCfg(
            prim_path="/World/light",
            spawn=sim_utils.DomeLightCfg(color=(0.75, 0.75, 0.75), intensity=3000.0),
        )

        # sensors
        contact_forces = ContactSensorCfg(
            prim_path="{ENV_REGEX_NS}/Robot/panda_leftfinger", update_period=0.0, history_length=6, debug_vis=True, track_air_time=True
    )

error occurs:

> Creating window for environment.
[INFO]: Completed setting up the environment...
Traceback (most recent call last):
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/standalone/workflows/rsl_rl/train.py", line 135, in <module>
    main()
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/standalone/workflows/rsl_rl/train.py", line 103, in main
    env = RslRlVecEnvWrapper(env)
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 89, in __init__
    self.env.reset()
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/_isaac_sim/kit/python/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py", line 61, in reset
    return self.env.reset(**kwargs)
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 242, in reset
    self._reset_idx(indices)
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 319, in _reset_idx
    self.scene.reset(env_ids)
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/scene/interactive_scene.py", line 333, in reset
    sensor.reset(env_ids)
  File "/home/rise-jjm-ubuntu/Dev/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/contact_sensor/contact_sensor.py", line 129, in reset
    self._data.net_forces_w[env_ids] = 0.0
TypeError: 'NoneType' object does not support item assignment

**Comment by timswim** [comment]
@HukoOo, Good day! How did you solve this error?

**Comment by Takui9** [comment]
hey, I got the same error. How did you solve this?
