### ISSUE TITLE
[Bug Report] IsaacLab throws exceptions when adding elements from IsaacSim menu

### ISSUE THREAD

**Issue by Jendker** [isaac-sim/IsaacLab#813]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

### Describe the bug

I am having issues when when adding elements from IsaacSim GUI menu.

### Steps to reproduce

1. Followed the installation steps from https://isaac-sim.github.io/IsaacLab/source/setup/installation/pip_installation.html
2. I used the CUDA 12 installation
3. For pip installation I had to add `isaacsim` to prevent the "Failed to resolve extension dependencies ... [‘omni.isaac.cortex’](dependency: 'omni.isaac.cortex')" error.
4. Run the `python source/standalone/tutorials/02_scene/create_scene.py` command
5. Wait for the scene to load - I can see the pendulums moving (as expected)
6. Try to add any element from the top-bar menu, such as Isaac Examples -> Sensors -> Contact leads to an exception and Isaac Sim window freeze. Selecting Simulation Output to "Fabric GPU" leads to the same issue.

```
python source/standalone/tutorials/02_scene/create_scene.py
[INFO][AppLauncher]: Loading experience file: /home/jorbik/Projects/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/../../../../../../apps/isaaclab.python.kit
[Warning] [omni.isaac.kit.simulation_app] Modules: ['omni.kit_app'] were loaded before SimulationApp was started and might not be loaded correctly.
[Warning] [omni.isaac.kit.simulation_app] Please check to make sure no extra omniverse or pxr modules are imported before the call to SimulationApp(...)
Starting kit application with the following args:  ['/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.kit/omni/isaac/kit/simulation_app.py', '/home/jorbik/Projects/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/app/../../../../../../apps/isaaclab.python.kit', '--/app/tokens/exe-path=/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni', '--/persistent/app/viewport/displayOptions=3094', '--/rtx/materialDb/syncLoads=True', '--/rtx/hydra/materialSyncLoads=True', '--/omni.kit.plugin/syncUsdLoads=True', '--/app/renderer/resolution/width=1280', '--/app/renderer/resolution/height=720', '--/app/window/width=1440', '--/app/window/height=900', '--/renderer/multiGpu/enabled=True', '--/app/fastShutdown=True', '--ext-folder', '/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts', '--ext-folder', '/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/apps', '--/renderer/activeGpu=0', '--/physics/cudaDevice=0', '--portable', '--/app/window/hideUi=False']
Passing the following args to the base kit application:  []
Loading user config located at: '/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/data/Kit/Isaac-Sim/4.1/user.config.json'
[Info] [carb] Logging to file: /home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/omni/logs/Kit/Isaac-Sim/4.1/kit_20240810_012935.log
2024-08-09 23:29:35 [0ms] [Warning] [omni.kit.app.plugin] No crash reporter present, dumps uploading isn't available.
[0.025s] [ext: omni.kit.async_engine-0.0.0] startup
[0.079s] [ext: omni.stats-1.0.1] startup
[0.080s] [ext: omni.client-1.1.0] startup
[0.100s] [ext: omni.datastore-0.0.0] startup
[0.101s] [ext: omni.blobkey-1.1.0] startup
[0.101s] [ext: omni.ujitso.default-1.0.0] startup
[0.101s] [ext: omni.hsscclient-0.0.0] startup
[0.101s] [ext: omni.rtx.shadercache.vulkan-1.0.0] startup
[0.102s] [ext: omni.assets.plugins-0.0.0] startup
[0.103s] [ext: omni.gpu_foundation-0.0.0] startup
[0.109s] [ext: carb.windowing.plugins-1.0.0] startup
[0.364s] [ext: omni.kit.renderer.init-0.0.0] startup
2024-08-09 23:29:36 [587ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-NVIDIA GPU: Intel(R) Graphics (RPL-S)
2024-08-09 23:29:36 [588ms] [Warning] [gpu.foundation.plugin] Skipping unsupported non-NVIDIA GPU: Intel(R) Graphics (RPL-S)

|---------------------------------------------------------------------------------------------|
| Driver Version: 555.42.06     | Graphics API: Vulkan
|=============================================================================================|
| GPU | Name                             | Active | LDA | GPU Memory | Vendor-ID | LUID       |
|     |                                  |        |     |            | Device-ID | UUID       |
|     |                                  |        |     |            | Bus-ID    |            |
|---------------------------------------------------------------------------------------------|
| 0   | NVIDIA RTX A4000                 | Yes: 0 |     | 16622   MB | 10de      | 0          |
|     |                                  |        |     |            | 24b0      | 2209c771.. |
|     |                                  |        |     |            | 1         |            |
|---------------------------------------------------------------------------------------------|
| 1   | Intel(R) Graphics (RPL-S)        |        |     | 23839   MB | 8086      | 0          |
|     |                                  |        |     |            | a780      | 868080a7.. |
|     |                                  |        |     |            | 0         |            |
|=============================================================================================|
| OS: 24.04 LTS (Noble Numbat) ubuntu, Version: 24.04.9, Kernel: 6.8.0-39-generic
| XServer Vendor: The X.Org Foundation, XServer Version: 12101011 (1.21.1.11)
| Processor: 13th Gen Intel(R) Core(TM) i9-13900K | Cores: 24 | Logical: 48
|---------------------------------------------------------------------------------------------|
| Total Memory (MB): 31786 | Free Memory: 26391
| Total Page/Swap (MB): 34719 | Free Page/Swap: 34719
|---------------------------------------------------------------------------------------------|
[1.387s] [ext: omni.kit.pipapi-0.0.0] startup
[1.387s] [ext: omni.kit.pip_archive-0.0.0] startup
[1.388s] [ext: omni.mtlx-0.1.0] startup
[1.388s] [ext: omni.usd.config-1.0.4] startup
[1.402s] [ext: omni.gpucompute.plugins-0.0.0] startup
[1.403s] [ext: omni.usd.libs-1.0.1] startup
[1.461s] [ext: omni.kit.loop-isaac-1.2.0] startup
[1.462s] [ext: omni.kit.test-0.0.0] startup
[1.482s] [ext: omni.kit.telemetry-0.5.0] startup
[1.497s] [ext: omni.appwindow-1.1.8] startup
[2.205s] [ext: omni.kit.renderer.core-1.0.1] startup
[26.347s] [ext: omni.kit.renderer.capture-0.0.0] startup
[26.348s] [ext: omni.kit.renderer.imgui-1.0.1] startup
[26.395s] [ext: omni.ui-2.23.11] startup
[26.402s] [ext: omni.kit.mainwindow-1.0.3] startup
[26.403s] [ext: carb.audio-0.1.0] startup
[26.405s] [ext: omni.uiaudio-1.0.0] startup
[26.405s] [ext: omni.kit.uiapp-0.0.0] startup
[26.405s] [ext: omni.usd.schema.semantics-0.0.0] startup
[26.477s] [ext: omni.usd.schema.audio-0.0.0] startup
[26.479s] [ext: omni.usd.schema.anim-0.0.0] startup
[26.490s] [ext: omni.usd.schema.forcefield-106.0.20] startup
[26.504s] [ext: omni.usd.schema.physx-106.0.20] startup
[26.521s] [ext: omni.usd.schema.omnigraph-1.0.0] startup
[26.525s] [ext: omni.usd.schema.scene.visualization-2.0.2] startup
[26.526s] [ext: omni.usd.schema.geospatial-0.0.0] startup
[26.528s] [ext: omni.usd.schema.isaac-2.1.0] startup
[26.532s] [ext: omni.kit.window.popup_dialog-2.0.24] startup
[26.535s] [ext: omni.usd_resolver-1.0.0] startup
[26.538s] [ext: omni.kit.widget.nucleus_connector-1.1.8] startup
[26.539s] [ext: omni.timeline-1.0.10] startup
[26.540s] [ext: omni.kit.usd_undo-0.1.8] startup
[26.540s] [ext: omni.usd.core-1.2.11] startup
[26.543s] [ext: omni.kit.widget.path_field-2.0.9] startup
[26.543s] [ext: omni.hydra.scene_delegate-0.3.3] startup
[26.548s] [ext: omni.kit.widget.browser_bar-2.0.10] startup
[26.549s] [ext: omni.activity.core-1.0.1] startup
[26.550s] [ext: omni.resourcemonitor-105.0.1] startup
[26.550s] [ext: omni.graph.exec-0.9.3] startup
[26.551s] [ext: omni.kit.actions.core-1.0.0] startup
[26.551s] [ext: usdrt.scenegraph-7.4.8] startup
[26.575s] [ext: omni.kit.audiodeviceenum-1.0.1] startup
[26.575s] [ext: omni.kit.exec.core-0.13.2] startup
[26.576s] [ext: omni.kit.commands-1.4.9] startup
[26.578s] [ext: omni.hydra.usdrt_delegate-7.4.7] startup
[26.592s] [ext: omni.kit.notification_manager-1.0.8] startup
[26.593s] [ext: omni.usd-1.11.2] startup
[26.624s] [ext: omni.kit.widget.nucleus_info-1.0.2] startup
[26.625s] [ext: omni.kit.helper.file_utils-0.1.8] startup
[26.625s] [ext: omni.kit.widget.options_menu-1.1.4] startup
[26.627s] [ext: omni.kit.search_core-1.0.5] startup
[26.627s] [ext: omni.kit.widget.filebrowser-2.10.48] startup
[26.629s] [ext: omni.kit.widget.options_button-1.0.2] startup
[26.629s] [ext: omni.ui.scene-1.9.3] startup
[26.632s] [ext: omni.kit.widget.search_delegate-1.0.4] startup
[26.632s] [ext: omni.kit.widget.context_menu-1.2.1] startup
[26.633s] [ext: omni.kit.clipboard-1.0.3] startup
[26.633s] [ext: omni.kit.window.filepicker-2.10.34] startup
[26.638s] [ext: omni.kit.widget.prompt-1.0.7] startup
[26.638s] [ext: omni.kit.widget.graph-1.12.8] startup
[26.640s] [ext: omni.kit.widget.live_session_management.ui-1.0.1] startup
[26.643s] [ext: omni.kit.window.drop_support-1.0.2] startup
[26.644s] [ext: omni.kit.graph.delegate.modern-1.10.6] startup
[26.644s] [ext: omni.kit.menu.utils-1.5.27] startup
[26.648s] [ext: omni.ujitso.processor.texture-1.0.0] startup
[26.648s] [ext: omni.kit.usd.layers-2.1.31] startup
[26.653s] [ext: omni.ujitso.client-0.0.0] startup
[26.653s] [ext: omni.inspect-1.0.1] startup
[26.654s] [ext: omni.iray.libs-0.0.0] startup
[26.657s] [ext: omni.kit.widget.searchfield-1.1.6] startup
[26.657s] [ext: omni.kit.primitive.mesh-1.0.16] startup
[26.658s] [ext: omni.kit.stage_template.core-1.1.21] startup
[26.659s] [ext: omni.volume-0.5.0] startup
[26.660s] [ext: omni.mdl.neuraylib-0.2.5] startup
[26.661s] [ext: omni.graph.core-2.170.3] startup
[26.663s] [ext: omni.hydra.rtx-0.2.0] startup
[26.673s] [ext: omni.hydra.engine.stats-1.0.2] startup
[26.676s] [ext: omni.kit.window.content_browser_registry-0.0.6] startup
[26.676s] [ext: omni.kit.stage_templates-1.2.3] startup
[26.677s] [ext: omni.kit.context_menu-1.8.0] startup
[26.678s] [ext: omni.kit.hotkeys.core-1.3.3] startup
[26.679s] [ext: omni.kit.widget.searchable_combobox-1.0.6] startup
[26.679s] [ext: omni.kit.widget.filter-1.1.4] startup
[26.680s] [ext: omni.kit.window.file_exporter-1.0.29] startup
[26.681s] [ext: omni.kit.window.file_importer-1.1.11] startup
[26.682s] [ext: omni.kit.widget.settings-1.1.1] startup
[26.682s] [ext: omni.kit.widget.highlight_label-1.0.2] startup
[26.683s] [ext: omni.kit.widget.stage-2.10.26] startup
[26.688s] [ext: omni.kit.window.file-1.3.52] startup
[26.690s] [ext: omni.kit.window.preferences-1.5.3] startup
[26.696s] [ext: omni.kit.collaboration.presence_layer-1.0.8] startup
[26.698s] [ext: omni.kit.window.property-1.11.1] startup
[26.700s] [ext: omni.kit.window.content_browser-2.9.14] startup
[26.709s] [ext: omni.kit.widget.live_session_management-1.2.18] startup
[26.710s] [ext: omni.graph.tools-1.78.0] startup
[26.719s] [ext: omni.kit.property.usd-3.21.28] startup
[26.724s] [ext: omni.graph-1.135.0] startup
[26.788s] [ext: omni.kit.raycast.query-1.0.5] startup
[26.795s] [ext: omni.kit.graph.delegate.default-1.2.2] startup
[26.796s] [ext: omni.kit.hydra_texture-1.2.6] startup
[26.801s] [ext: omni.mdl-52.0.1] startup
[26.815s] [ext: omni.kit.graph.editor.core-1.5.3] startup
[26.816s] [ext: omni.kit.widget.viewport-106.0.3] startup
[26.820s] [ext: omni.kit.viewport.registry-104.0.6] startup
[26.821s] [ext: omni.kit.material.library-1.4.4] startup
[26.824s] [ext: omni.kit.graph.widget.variables-2.1.0] startup
[26.826s] [ext: omni.kit.viewport.window-106.0.8] startup
[26.836s] [ext: omni.kit.widget.text_editor-1.0.2] startup
[26.838s] [ext: omni.kit.window.extensions-1.4.9] startup
[26.840s] [ext: omni.kit.viewport.utility-1.0.17] startup
[26.841s] [ext: omni.kit.graph.usd.commands-1.3.1] startup
[26.842s] [ext: omni.graph.ui-1.70.0] startup
[26.848s] [ext: omni.isaac.kit-1.13.0] startup
[26.849s] [ext: omni.graph.window.core-1.109.0] startup
[26.855s] [ext: omni.kit.manipulator.camera-105.0.5] startup
[26.858s] [ext: omni.kit.manipulator.viewport-107.0.0] startup
[26.859s] [ext: omni.graph.window.generic-1.24.0] startup
[26.862s] [ext: omni.convexdecomposition-106.0.20] startup
[26.866s] [ext: omni.graph.visualization.nodes-2.1.1] startup
[26.870s] [ext: omni.graph.action_core-1.1.4] startup
[26.875s] [ext: omni.physx.foundation-106.0.20] startup
[26.876s] [ext: omni.kvdb-106.0.20] startup
[26.877s] [ext: omni.graph.action_nodes-1.23.0] startup
[26.883s] [ext: omni.usdphysics-106.0.20] startup
[26.886s] [ext: omni.localcache-106.0.20] startup
[26.887s] [ext: omni.graph.action-1.102.1] startup
[26.888s] [ext: omni.physx.cooking-106.0.20] startup
[26.896s] [ext: omni.kit.ui.actions-1.0.1] startup
[26.897s] [ext: omni.physx-106.0.20] startup
[26.907s] [ext: omni.physics.tensors-106.0.20] startup
[26.922s] [ext: omni.isaac.version-1.1.0] startup
[26.926s] [ext: omni.ui_query-1.1.2] startup
[26.928s] [ext: omni.warp.core-1.2.1] startup
[26.969s] [ext: omni.physx.tensors-106.0.20] startup
[26.975s] [ext: omni.physx.stageupdate-106.0.20] startup
[26.977s] [ext: omni.isaac.nucleus-0.3.0] startup
[26.978s] [ext: omni.kit.ui_test-1.2.18] startup
[26.979s] [ext: omni.isaac.core-3.18.1] startup
[27.586s] [ext: omni.kit.numpy.common-0.1.2] startup
[27.588s] [ext: omni.isaac.ui-0.16.0] startup
[27.590s] [ext: omni.kit.menu.common-1.1.5] startup
[27.591s] [ext: omni.isaac.dynamic_control-1.3.8] startup
[27.596s] [ext: omni.isaac.menu-0.5.0] startup
[27.598s] [ext: omni.kit.window.cursor-1.1.2] startup
[27.600s] [ext: omni.graph.window.action-1.26.0] startup
[27.603s] [ext: omni.kit.viewport.menubar.core-106.0.2] startup
[27.613s] [ext: omni.kit.viewport.actions-106.0.3] startup
[27.615s] [ext: omni.kit.widget.toolbar-1.6.2] startup
[27.620s] [ext: omni.kit.manipulator.transform-104.7.5] startup
[27.622s] [ext: omni.kit.viewport.menubar.display-106.0.2] startup
[27.623s] [ext: omni.debugdraw-0.1.3] startup
[27.627s] [ext: omni.kit.manipulator.tool.snap-1.4.5] startup
[27.630s] [ext: omni.kit.manipulator.selector-1.1.1] startup
[27.632s] [ext: omni.usdphysics.ui-106.0.20] startup
[27.650s] [ext: omni.physx.commands-106.0.20] startup
[27.653s] [ext: omni.graph.image.core-0.3.2] startup
[27.656s] [ext: omni.kit.viewport.manipulator.transform-106.0.1] startup
[27.657s] [ext: omni.physx.ui-106.0.20] startup
[27.676s] [ext: omni.kit.property.material-1.9.4] startup
[27.679s] [ext: omni.fabric.commands-1.1.4] startup
[27.683s] [ext: omni.graph.image.nodes-1.0.2] startup
[27.684s] [ext: omni.kit.manipulator.prim.core-107.0.3] startup
[27.688s] [ext: omni.kit.property.physx-106.0.20] startup
[27.734s] [ext: omni.physx.demos-106.0.20] startup
[27.745s] [ext: omni.kit.widget.layers-1.7.9] startup
[27.752s] [ext: omni.graph.nodes-1.143.0] startup
Warning: Possible version incompatibility. Attempting to load omni::fabric::IPath with version v0.2 against v0.1.
[27.760s] [ext: omni.kit.manipulator.prim.fabric-106.0.1] startup
[27.762s] [ext: omni.kit.manipulator.prim.usd-106.0.1] startup
[27.763s] [ext: omni.physx.vehicle-106.0.20] startup
[27.782s] [ext: omni.graph.ui_nodes-1.25.1] startup
Warning: Possible version incompatibility. Attempting to load omni::fabric::IPath with version v0.2 against v0.1.
[27.789s] [ext: omni.kit.window.toolbar-1.6.1] startup
[27.795s] [ext: omni.kit.manipulator.selection-104.0.9] startup
[27.797s] [ext: omni.kit.manipulator.prim-106.0.0] startup
[27.797s] [ext: omni.physx.camera-106.0.20] startup
[27.807s] [ext: omni.graph.bundle.action-2.0.4] startup
[27.809s] [ext: omni.physx.supportui-106.0.20] startup
[27.821s] [ext: omni.physx.telemetry-106.0.20] startup
[27.828s] [ext: omni.physx.graph-106.0.20] startup
[27.844s] [ext: omni.physx.cct-106.0.20] startup
[27.854s] [ext: omni.command.usd-1.0.3] startup
[27.857s] [ext: omni.kit.widget.material_preview-1.0.16] startup
[27.861s] [ext: omni.physx.bundle-106.0.20] startup
[27.862s] [ext: omni.sensors.tiled-0.0.4] startup
[27.865s] [ext: omni.syntheticdata-0.6.7] startup
[27.890s] [ext: omni.warp-1.2.1] startup
[27.896s] [ext: omni.kit.window.material_graph-1.8.15] startup
[28.028s] [ext: omni.graph.scriptnode-1.19.1] startup
[28.030s] [ext: omni.sensors.nv.common-1.2.2-isaac] startup
[28.038s] [ext: omni.isaac.debug_draw-1.1.0] startup
[28.042s] [ext: omni.replicator.core-1.11.14] startup
2024-08-09 23:30:03 [28,047ms] [Warning] [omni.replicator.core.scripts.annotators] Annotator PostProcessDispatch is already registered, overwriting annotator template
Warp 1.2.1 initialized:
   CUDA Toolkit 11.8, Driver 12.5
   Devices:
     "cpu"      : "x86_64"
     "cuda:0"   : "NVIDIA RTX A4000" (16 GiB, sm_86, mempool enabled)
   Kernel cache:
     /home/jorbik/.cache/warp/1.2.1
[28.115s] [ext: omni.kit.menu.create-1.0.13] startup
[28.117s] [ext: omni.sensors.nv.materials-1.2.1-isaac] startup
[28.119s] [ext: omni.isaac.range_sensor-3.1.1] startup
[28.129s] [ext: omni.isaac.core_nodes-1.16.1] startup
[28.137s] [ext: omni.sensors.nv.wpm-1.2.1-isaac] startup
[28.139s] [ext: omni.kit.actions.window-1.1.1] startup
[28.142s] [ext: omni.kit.selection-0.1.4] startup
[28.143s] [ext: omni.sensors.nv.radar-1.2.1-isaac] startup
[28.147s] [ext: omni.sensors.nv.lidar-1.2.2-isaac] startup
[28.152s] [ext: omni.kit.menu.file-1.1.10] startup
[28.155s] [ext: omni.kit.menu.edit-1.1.24] startup
[28.163s] [ext: omni.isaac.sensor-12.7.1] startup
[28.225s] [ext: omni.kit.hotkeys.window-1.4.5] startup
[28.239s] [ext: omni.kit.property.isaac-0.2.3] startup
[28.241s] [ext: omni.kit.property.layer-1.1.6] startup
[28.245s] [ext: omni.kit.stage_column.payload-2.0.0] startup
[28.250s] [ext: omni.kit.stage_column.variant-1.0.13] startup
[28.254s] [ext: omni.kit.stagerecorder.core-105.0.5] startup
[28.262s] [ext: omni.rtx.window.settings-0.6.16] startup
[28.271s] [ext: omni.kit.widget.live-2.1.6] startup
[28.274s] [ext: omni.kit.viewport.menubar.camera-105.1.8] startup
[28.281s] [ext: omni.kit.viewport.menubar.render-106.1.3] startup
[28.285s] [ext: omni.kit.viewport.menubar.settings-106.0.1] startup
[28.290s] [ext: omni.kit.viewport.rtx-104.0.1] startup
[28.291s] [ext: omni.kit.widget.cache_indicator-2.0.8] startup
[28.316s] [ext: omni.kit.property.audio-1.0.11] startup
[28.317s] [ext: omni.kit.widget.calendar-1.0.8] startup
[28.319s] [ext: omni.kit.widget.stage_icons-1.0.4] startup
[28.319s] [ext: omni.hydra.scene_api-0.1.2] startup
[28.325s] [ext: omni.kit.property.geometry-1.3.0] startup
[28.327s] [ext: omni.kit.property.camera-1.0.6] startup
[28.328s] [ext: omni.kit.widget.extended_searchfield-1.0.28] startup
[28.332s] [ext: omni.kit.window.stage-2.5.10] startup
[28.335s] [ext: omni.kit.property.transform-1.5.1] startup
[28.338s] [ext: omni.kit.property.render-1.1.1] startup
[28.339s] [ext: omni.kit.property.light-1.0.8] startup
[28.340s] [ext: omni.kit.window.commands-0.2.5] startup
[28.341s] [ext: omni.kit.widget.timeline-105.0.1] startup
[28.342s] [ext: omni.kit.menu.stage-1.2.5] startup
[28.343s] [ext: omni.kit.property.bundle-1.2.11] startup
[28.344s] [ext: omni.kit.window.status_bar-0.1.6] startup
[28.348s] [ext: omni.kit.window.title-1.1.3] startup
[28.348s] [ext: omni.replicator.isaac-1.15.0] startup
[28.356s] [ext: omni.replicator.replicator_yaml-2.0.5] startup
[28.368s] [ext: omni.rtx.settings.core-0.6.0] startup
[28.371s] [ext: omni.kit.window.console-0.2.12] startup
[28.380s] [ext: semantics.schema.editor-0.3.6] startup
[28.382s] [ext: semantics.schema.property-1.0.3] startup
[28.383s] [ext: omni.kit.window.script_editor-1.7.6] startup
[28.387s] [ext: omni.kit.profiler.window-2.2.1] startup
2024-08-09 23:30:03 [28,382ms] [Warning] [omni.kit.profiler.window] remove _SpanInstance.__lt__ and use insort 'key' arg instead
[28.395s] [ext: omni.isaac.utils-1.0.1] startup
[28.398s] [ext: omni.isaac.cloner-0.8.1] startup
[28.400s] [ext: omni.kit.window.stats-0.1.6] startup
[28.402s] [ext: isaaclab.python-1.1.0] startup
[28.404s] Simulation App Starting
[30.116s] app ready
[31.124s] Simulation App Startup Complete
[31.444s] [ext: omni.physx.fabric-106.0.20] startup
2024-08-09 23:30:11 [36,135ms] [Warning] [omni.hydra.scene_delegate.plugin] Calling getBypassRenderSkelMeshProcessing for prim /World/envs/env_0/Robot/slider/visuals.proto_mesh_0_id0 that has not been populated
[INFO]: Setup complete...
[INFO]: Resetting robot state...
[51.518s] Simulation is stopped. The app will keep running with physics disabled. Press Ctrl+C or close the window to exit the app.
2024-08-09 23:30:27 [51,512ms] [Error] [asyncio] Exception in callback Task.task_wakeup(<Future finished result=None>)
handle: <Handle Task.task_wakeup(<Future finished result=None>)>
Traceback (most recent call last):
  File "/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-2' coro=<NotificationManager.on_startup.<locals>.timer_fn() running at /home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.kit.notification_manager/omni/kit/notification_manager/manager.py:182> wait_for=<Future finished result=None>> while another task <Task pending name='Task-138' coro=<Contact_sensor_demo.create_scenario() running at /home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.sensor/omni/isaac/sensor/scripts/samples/contact_sensor.py:146>> is being executed.
2024-08-09 23:30:33 [58,397ms] [Error] [asyncio] Exception in callback <TaskStepMethWrapper object at 0x779cbd7da980>()
handle: <Handle <TaskStepMethWrapper object at 0x779cbd7da980>()>
Traceback (most recent call last):
  File "/home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-139' coro=<CacheStateMenu._on_update.<locals>._ping_cache() running at /home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/extscache/omni.kit.widget.cache_indicator/omni/kit/widget/cache_indicator/cache_state_menu.py:157>> while another task <Task pending name='Task-138' coro=<Contact_sensor_demo.create_scenario() running at /home/jorbik/miniconda3/envs/isaaclab/lib/python3.10/site-packages/isaacsim/exts/omni.isaac.sensor/omni/isaac/sensor/scripts/samples/contact_sensor.py:146>> is being executed.
```

-->

### System Info

- Commit: [6451d23](https://github.com/isaac-sim/IsaacLab/commit/6451d235785780167f80c14bb9d635d20aff9b29)
- Isaac Sim Version: 4.1.0
- OS: Ubuntu 24.04
- GPU: RTX A4000
- CUDA: 12.5
- GPU Driver: 555.42.06

### Additional context

The same menu Isaac Examples -> Sensors -> Contact works fine I launch the software using `isaacsim omni.isaac.sim.python.kit` mentioned in https://isaac-sim.github.io/IsaacLab/source/setup/installation/verifying_installation.html#isaac-sim-installed-from-pip

Screenshot after trying to insert the sensor:
<img width="1428" alt="Screenshot 2024-08-11 at 22 58 29" src="https://github.com/user-attachments/assets/8b07234d-72ed-4b7a-b8ed-71e37a7f8bab">

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

### Acceptance Criteria

Add the criteria for which this task is considered **done**. If not known at issue creation time, you can add this once the issue is assigned.

- [ ] I am able to use the GUI to add IsaacSim elements when launching an IsaacLab scene.

Please let me know if that's an expected behavior and the scene entities and simulation settings are not designed to be changed on runtime through GUI.

**Comment by RandomOakForest** [comment]
Our apologies we couldn't follow up in a timely manner. Please reopen the issue if you still see this using Isaac Sim 4.2 and Isaac Lab 1.4.0. Thank you.
