### ISSUE TITLE
[Question] PLZ HELP!!! Can not register g1 in gymnasium.

### ISSUE THREAD

**Issue by ItsBean** [isaac-sim/IsaacLab#927]
### Question
Here is my code to register the humanoid robot to the gym env:
```
import gymnasium as gym
from omni.isaac.lab_tasks.manager_based.locomotion.velocity.config.g1.rough_env_cfg import G1RoughEnvCfg
from omni.isaac.lab.envs import ManagerBasedRLEnv
# skrl_path="source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/manager_based/locomotion/velocity/config/g1/agents/skrl_rough_ppo_cfg.yaml"
gym.register(
    id="Isaac-Velocity-Rough-G1-v0",
    # entry_point="omni.isaac.lab.envs:ManagerBasedRLEnv",
    entry_point=ManagerBasedRLEnv,
    disable_env_checker=True,
    kwargs={
        "env_cfg_entry_point": G1RoughEnvCfg,
    },
)
```

Execute `./isaaclab.sh -p source/standalone/workflows/skrl/skrl_registration.py`
then here is the bug report:

```
[INFO] Using python from: /home/xxx/anaconda3/envs/isaaclab/bin/python                                                                   
Traceback (most recent call last):
  File "/home/xxx/IsaacLab/source/standalone/workflows/skrl/skrl_registration.py", line 3, in <module>
    from omni.isaac.lab_tasks.manager_based.locomotion.velocity.config.g1.rough_env_cfg import G1RoughEnvCfg
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/__init__.py", line 25, in <module>
    from .utils import import_packages
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/__init__.py", line 9, in <module>
    from .parse_cfg import get_checkpoint_path, load_cfg_from_registry, parse_env_cfg
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab_tasks/omni/isaac/lab_tasks/utils/parse_cfg.py", line 16, in <module>
    from omni.isaac.lab.envs import ManagerBasedRLEnvCfg
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/__init__.py", line 38, in <module>
    from . import mdp, ui
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/__init__.py", line 18, in <module>
    from .actions import *  # noqa: F401, F403
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/actions/__init__.py", line 8, in <module>
    from .actions_cfg import *
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/mdp/actions/actions_cfg.py", line 9, in <module>
    from omni.isaac.lab.managers.action_manager import ActionTerm, ActionTermCfg
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/__init__.py", line 13, in <module>
    from .action_manager import ActionManager, ActionTerm
  File "/home/xxx/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/action_manager.py", line 18, in <module>
    import omni.kit.app
ModuleNotFoundError: No module named 'omni.kit'
```

**Comment by zoctipus** [comment]
If I remember applaunch needs to be initialized before omni.kit module becomes available

**Comment by pascal-roth** [comment]
@ItsBean did it solve your error when you activate the AppLauncher beforehand? Then we can close this issue.
